import type { Metadata } from "next";
import { Inter, IBM_Plex_Serif } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,

} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });
const ibm = IBM_Plex_Serif({subsets:["latin"], weight:["500","600","700"], variable:"--ibm" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
 
    <html lang="en">
      <head>

      </head>
      <body className={inter.className +" "+ ibm.variable}>
      <ClerkProvider>
        {children}
        </ClerkProvider>
        </body>
    </html>
   
  );
}
